services:
  # Audiobookshelf is a self-hosted audiobook and podcast server
  audiobookshelf:
    image: advplyr/audiobookshelf:2.28.0
    container_name: audiobookshelf
    environment:
      - AUDIOBOOKSHELF_UID=99
      - AUDIOBOOKSHELF_GID=100
      # Controls session expirations for logged in users
      - ACCESS_TOKEN_EXPIRY=86400 # Bump 12 hours to 1 day
      - REFRESH_TOKEN_EXPIRY=2592000 # Bump 7 days default to 30 days
    ports:
      - 13378:80
    volumes:
      - ${INSTALL_DIRECTORY}/config/audiobookshelf/config:/config
      - ${INSTALL_DIRECTORY}/config/audiobookshelf/metadata:/metadata
      - ${MEDIA_DIRECTORY}/audiobooks:/audiobooks
    restart: always
  calibre-web:
    image: lscr.io/linuxserver/calibre-web:0.6.25
    container_name: calibre-web
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
      # - DOCKER_MODS=linuxserver/mods:universal-calibre #optional
      # - OAUTHLIB_RELAX_TOKEN_SCOPE=1 #optional
    volumes:
      - ${INSTALL_DIRECTORY}/config/calibre-web:/config
      - ${MEDIA_DIRECTORY}/books:/books
    ports:
      - 8083:8083
    restart: unless-stopped
